### ISSUE TITLE
Fastboot support

### ISSUE THREAD

**Issue by kennstenicht** [bgentry/ember-apollo-client#65] opened 2017-10-21 08:19 UTC
After the latest release I hopped, that this addon now has a fastboot support, but i get the following error: `Error: Network error: XMLHttpRequest is not defined`

I tried to set up a new ember app(2.16.0) with just ember-cli-fastboot(1.1.0) and ember-apollo-client(0.5.2) installed, but i still get the same error.

**Comment by bgentry** [comment] 2017-10-21 15:40
Do you have a sample app we can reference to help debug this?

**Comment by kennstenicht** [comment] 2017-10-22 09:06
I created a new repo with my small sample app. https://github.com/kennstenicht/ember-apollo-fastboot-test

**Comment by villander** [comment] 2017-10-29 15:28
@bgentry i have this error too. I tried use [Apollo Fetch](https://github.com/apollographql/apollo-fetch#apollo-integration) and integrate with ember-apollo, but I was not very successful. Do you have any idea how I am substituting XMLHttpRequest for fetch API in apollo-client?

**Comment by villander** [comment] 2017-10-31 23:00
@bgentry you have any suggestion for this problem with SSR?

**Comment by viniciussbs** [comment] 2017-10-31 23:23
I think this issue will be easier to address with Apollo Link after we update the addon to Apollo Client 2.0 - #54

**Comment by villander** [comment] 2017-11-01 01:08
I do not think so @viniciussbs, because the problem is the fastboot don't support `XMLHttpRequest` and Apollo Client 2.0  continues using `XMLHttpRequest`

**Comment by viniciussbs** [comment] 2017-11-01 14:40
@villander Apollo Client 2.0 relies on Apollo Link, that relies on Fetch. [It deals better with global Fetch and let's you pass your on Fetch implementation](https://www.apollographql.com/docs/link/links/http.html#Global-Fetch).

**Comment by villander** [comment] 2017-11-01 14:45
Nice, we go start migration 🏎

**Comment by viniciussbs** [comment] 2017-11-08 12:30
Maybe something like this but inside the service should solve the fetch problem:

https://github.com/bgentry/ember-apollo-client/blob/master/tests/helpers/module-for-acceptance.js#L16-L20

**Comment by villander** [comment] 2017-11-11 18:30
@viniciussbs it's don't works, because SSR don't support browser API as `window`. What makes sense is to [overwrite apollo's networkInterface](https://github.com/apollographql/apollo-client/issues/1827) or migrate to version 2.0

https://ember-fastboot.com/docs/addon-author-guide#common-causes

**Comment by bgentry** [comment] 2018-02-16 21:54
This was merged in #79. @villander created a sample fastboot app here: https://github.com/villander/ember-mvp

Check the readme for more info. Cheers 🍻

**Closed by bgentry** 2018-02-16 21:54 UTC
