### ISSUE TITLE
redux error about minified code / NODE_ENV === 'production'

### ISSUE THREAD

**Issue by viniciussbs** [bgentry/ember-apollo-client#7] opened 2017-01-24 22:21 UTC
After shipping a new version of my app using ember-apollo-client to production, I'm facing this message on browser's console:

> You are currently using minified code outside of NODE_ENV === 'production'. This means that you are running a slower development build of Redux. You can use loose-envify (https://github.com/zertosh/loose-envify) for browserify or DefinePlugin for webpack (http://stackoverflow.com/questions/30030031) to ensure you have the correct code for your production build.

**Comment by bgentry** [comment] 2017-01-24 22:28
I can confirm that I'm also seeing this on my app. Hadn't opened the console in prod for awhile.

Since @dfreeman did the packaging work here, maybe he has an idea about the cause?

**Comment by dfreeman** [comment] 2017-01-24 23:38
Not super familiar with what Redux is doing internally there, but I can take a look later tonight. (Haven't forgotten I owe you an answer on #5, too 🙂)

**Comment by bgentry** [comment] 2017-01-24 23:50
@dfreeman you don't owe me anything! but would of course love your input if you have time 😄

**Comment by bgentry** [comment] 2017-01-27 00:51
Fixed by @dfreeman in #8. Thanks for reporting :v:

**Closed** 2017-01-27 00:50 UTC
Labels: bug
