### ISSUE TITLE
JSON Response getting truncated

### ISSUE THREAD

**Issue by aparna-v** [bgentry/ember-apollo-client#125] opened 2018-04-10 09:14 UTC
We have a query in our GraphQL server that can potentially return a very large JSON array ( we are trying to get CRUD permissions for UI elements).
Based on our tests, the response size is around 200K. 
When we run this query in GraphiQL, the query works fine.
But the response gets truncated when we try to query through our Ember app using Apollo client
We find that this JSON gets truncated, at approx around 130K. Response parsing fails due to this. 

Our Query
```
return get(this, 'apollo')
  .watchQuery({
    query: myImportedQuery,
    variables: {
      // my query specific variables
    },
    fetchPolicy: 'network-only'
  })
  .then((response) => {
    return response
  })
```
This is the error we get: 
```
{
  "errors": [
    {
      "message": "Unexpected end of JSON input",
      "locations": [
        "SyntaxError: Unexpected end of JSON input\n    at JSON.parse (<anonymous>)\n    at http://localhost:4200/assets/vendor.js:75140:25\n    at tryCatcher (http://localhost:4200/assets/vendor.js:55417:21)\n    at invokeCallback (http://localhost:4200/assets/vendor.js:55595:33)\n    at publish (http://localhost:4200/assets/vendor.js:55581:9)\n    at http://localhost:4200/assets/vendor.js:46660:16\n    at invoke (http://localhost:4200/assets/vendor.js:14164:24)\n    at Queue.flush (http://localhost:4200/assets/vendor.js:14084:25)\n    at DeferredActionQueues.flush (http://localhost:4200/assets/vendor.js:14237:31)\n    at Backburner.end (http://localhost:4200/assets/vendor.js:14369:42)"
      ]
    }
  ]
}

```

Our chrome dev console:
![screen shot 2018-04-10 at 4 07 51 pm](https://user-images.githubusercontent.com/5926004/38552682-8b45a0c4-3cda-11e8-8430-420a5bc05471.png)

What could be causing this issue?
Is there any header we are missing?
Any setting in Apollo client which may affect the size of response it can parse?

We use https://github.com/graphql-java in the backend.
Since GraphiQL is able to get the entire response, we doubt if its a server issue.

**Comment by bgentry** [comment] 2018-04-10 15:41
It’s going to be difficult to track this down without a reproduction. But actually one thing that would help a bunch is to figure out if this happens inside Apollo Client itself or in this addon.

Can you dig a bit deeper with the debugger to figure that out? You could set some breakpoints inside the `apollo.js` service file from this addon and then see if the error happens before or after Apollo Client returns a response.

**Comment by aparna-v** [comment] 2018-04-11 09:27
@bgentry we added a catch block to the query function like so:
```
query(opts, resultKey) {
    return this._waitFor(
      this.client
        .query(opts)
        .then((result) => {
          let response = result.data
          console.log('Result Key', resultKey)
          if (!isNone(resultKey)) {
            console.log('Inside Result Key', resultKey)
            response = get(response, resultKey)
          }
          return RSVP.resolve(copy(response, true))
        })
        .catch(function(e) {
          console.log(e)
        })
    )
  }
```
Turns out we get the 'Unexpected end of JSON input' error here.

**Comment by bgentry** [comment] 2018-04-11 16:58
Right, it’s not surprising that the catch you have catches the error as it’s clearly thrown somewhere within the query. My question is _where_ inside the query it’s coming from.

Can you set a breakpoint inside as I suggested to see if it’s coming from Apollo Client itself or from something we’re doing in the addon?

**Comment by aparna-v** [comment] 2018-04-12 11:50
ApolloError (-apollo-client-bundle.js:7348)
(anonymous) (-apollo-client-bundle.js:16475)
(anonymous) (-apollo-client-bundle.js:16856)
(anonymous) (-apollo-client-bundle.js:16855)
QueryManager.broadcastQueries (-apollo-client-bundle.js:16850)
(anonymous) (-apollo-client-bundle.js:16424)
Promise.catch (async)
QueryManager.fetchQuery (-apollo-client-bundle.js:16415)
QueryManager.startQuery (-apollo-client-bundle.js:16754)
ObservableQuery.setUpQuery (-apollo-client-bundle.js:7287)
ObservableQuery.onSubscribe (-apollo-client-bundle.js:7256)
(anonymous) (-apollo-client-bundle.js:6995)
Subscription (-apollo-client-bundle.js:23968)
subscribe (-apollo-client-bundle.js:24091)
(anonymous) (-apollo-client-bundle.js:7027)
ObservableQuery.result (-apollo-client-bundle.js:7011)
(anonymous) (-apollo-client-bundle.js:16620)
QueryManager.query (-apollo-client-bundle.js:16617)
ApolloClient.query (-apollo-client-bundle.js:16081)
query (apollo.js:199)
getLoanPermissions (service.js:37)
getCodePermission (service.js:51)
(anonymous) (ability.js:17)
ComputedPropertyPrototype.get (ember-metal.js:3390)
get (ember-metal.js:2761)
get (observable.js:38)
can (can.js:42)
can (can.js:11)
(anonymous) (route.js:12)
ComputedPropertyPrototype.get (ember-metal.js:3390)
get (ember-metal.js:2761)
get (observable.js:38)
getHouseIncomeTable (route.js:80)
Ember.get.watchQuery.then (route.js:35)
tryCatcher (rsvp.js:215)
invokeCallback (rsvp.js:393)
publish (rsvp.js:379)
(anonymous) (rsvp.js:14)
invoke (backburner.js:205)
flush (backburner.js:125)
flush (backburner.js:278)
end (backburner.js:410)
Backburner._boundAutorunEnd (backburner.js:372)
setTimeout (async)
Backburner.platform.next (backburner.js:360)
_ensureInstance (backburner.js:884)
schedule (backburner.js:499)
(anonymous) (rsvp.js:13)
fulfill (rsvp.js:330)
resolve (rsvp.js:305)
(anonymous) (rsvp.js:423)
reader.onload (ember-fetch.js:179)
load (async)
(anonymous) (ember-fetch.js:178)
initializePromise (rsvp.js:418)
Promise (rsvp.js:897)
fileReaderReady (ember-fetch.js:177)
readBlobAsText (ember-fetch.js:196)
Body.text (ember-fetch.js:291)
(anonymous) (-apollo-client-bundle.js:17581)
tryCatcher (rsvp.js:215)
invokeCallback (rsvp.js:393)
publish (rsvp.js:379)
(anonymous) (rsvp.js:14)
invoke (backburner.js:205)
flush (backburner.js:125)
flush (backburner.js:278)
end (backburner.js:410)
Backburner._boundAutorunEnd (backburner.js:372)
setTimeout (async)
Backburner.platform.next (backburner.js:360)
_ensureInstance (backburner.js:884)
schedule (backburner.js:499)
(anonymous) (rsvp.js:13)
fulfill (rsvp.js:330)
handleMaybeThenable (rsvp.js:295)
resolve (rsvp.js:303)
(anonymous) (rsvp.js:423)
xhr.onload (ember-fetch.js:449)
load (async)
(anonymous) (ember-fetch.js:441)
initializePromise (rsvp.js:418)
Promise (rsvp.js:897)
self.fetch (ember-fetch.js:437)
self.default (ember-fetch.js:495)
(anonymous) (-apollo-client-bundle.js:17753)
Subscription (-apollo-client-bundle.js:23968)
subscribe (-apollo-client-bundle.js:24091)
(anonymous) (-apollo-client-bundle.js:15312)
Promise.then (async)
(anonymous) (-apollo-client-bundle.js:15311)
Subscription (-apollo-client-bundle.js:23968)
subscribe (-apollo-client-bundle.js:24091)
(anonymous) (-apollo-client-bundle.js:17490)
Subscription (-apollo-client-bundle.js:23968)
subscribe (-apollo-client-bundle.js:24091)
(anonymous) (-apollo-client-bundle.js:16869)
QueryManager.fetchRequest (-apollo-client-bundle.js:16867)
QueryManager.fetchQuery (-apollo-client-bundle.js:16409)
QueryManager.startQuery (-apollo-client-bundle.js:16754)
ObservableQuery.setUpQuery (-apollo-client-bundle.js:7287)
ObservableQuery.onSubscribe (-apollo-client-bundle.js:7256)
(anonymous) (-apollo-client-bundle.js:6995)
Subscription (-apollo-client-bundle.js:23968)
subscribe (-apollo-client-bundle.js:24091)
_waitFor.Ember.RSVP.Promise (apollo.js:179)
initializePromise (rsvp.js:418)
Promise (rsvp.js:897)
watchQuery (apollo.js:177)
model (route.js:20)
deserialize (route.js:945)
applyHook (router.js:212)
runSharedModelHook (router.js:665)
getModel (router.js:899)
tryCatcher (rsvp.js:215)
invokeCallback (rsvp.js:393)
publish (rsvp.js:379)
(anonymous) (rsvp.js:14)
invoke (backburner.js:205)
flush (backburner.js:125)
flush (backburner.js:278)
end (backburner.js:410)
Backburner._boundAutorunEnd (backburner.js:372)
setTimeout (async)
Backburner.platform.next (backburner.js:360)
_ensureInstance (backburner.js:884)
schedule (backburner.js:499)
run.schedule (ember-metal.js:4547)
waitForDOMReady (application.js:354)
init (application.js:325)
superWrapper (ember-utils.js:420)
Class (core_object.js:118)
_ClassMixinProps.create (core_object.js:277)
(anonymous) (app-boot.js:2)```

**Comment by bgentry** [comment] 2018-04-25 18:52
Unfortunately the stacktrace you posted doesn't really help me because I can't see your JS bundle. I don't know what code is on those line numbers unless you tell me, which is what I was hoping you could do. I'm going to close this for now but if you're able to gather more info that indicates this is an issue with ember-apollo-client, please reopen.

Have you tried running it in the Apollo Chrome devtools extension? They have an embedded graphiql that I believe uses Apollo Client to execute the query.

**Closed by bgentry** 2018-04-25 18:52 UTC
