### ISSUE TITLE
Expose apollo-link-error

### ISSUE THREAD

**Issue by nizarayari** [bgentry/ember-apollo-client#144] opened 2018-07-10 00:47 UTC
It would be great to expose apollo-link-error as well. Would you like me to submit  a PR?

**Comment by viniciussbs** [comment] 2018-07-10 14:03
I think `apollo-link-error` is a good one to be exposed by default.

P.S.: @bgentry you have a fork of `ember-cli-deploy-rollbar` for the source maps uploading, so I guess you are using Rollbar when handling errors. I would like to see how you are dealing with it. Are you using `apollo-link-error`?

**Comment by bgentry** [comment] 2018-07-10 17:40
I haven't yet updated my codebase to use apollo-link-error, but that looks like the correct thing to do. I think it makes sense to include it out-of-the-box. Want to PR that?

**Comment by bgentry** [comment] 2018-07-10 17:40
Also, this is a dupe of #137 so I'm closing it in favor of that issue. Please continue the discussion there. Cheers :v:

**Closed by bgentry** 2018-07-10 17:40 UTC
